version: '3.3'

services:

  mysql:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_MYSQL_PASSWORD}
    networks:
      - net
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: solidnerd/bookstack
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - DB_HOST=mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=${BOOKSTACK_MYSQL_PASSWORD}
    volumes:
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/public/storage
    networks:
      - net
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:bookstack.${DOMAIN}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

  db-backup:
    image: mariadb:10
    environment:
      - DB_HOST=mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=${BOOKSTACK_MYSQL_PASSWORD}
    networks:
      - net
    volumes:
      - database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'

volumes:
  mysql-data:
    driver: local
  uploads:
    driver: local
  storage-uploads:
    driver: local
  database-dump:
    driver: local

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
