version: '3.3'
services:
  homeassistant:
    restart: unless-stopped
    image: homeassistant/home-assistant
    devices:
      - dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0
    ports:
      - "8123:8123"
    volumes:
      - /home/joe/data/homeassistant:/config
      - /etc/timezone:/etc/localtime:ro
