version: '3.7'
services:
  app:
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE="traefik-consul_traefik traefik-consul_consul"
      #- NOTIFIERS=tgram://${TELEGRAM_BOTTOKEN}/${TELEGRAM_CHATID}
      - NOTIFIERS=mailgun://joe@${MAILGUN_DOMAIN}/${MAILGUN_API}/${EMAIL}
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
