version: '3.7'
services:
  app:
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=debug
      - SELF_UPDATE=true
      - IGNORE="traefik bitwarden freepbx"
      #- NOTIFIERS=tgram://${TELEGRAM_BOTTOKEN}/${TELEGRAM_CHATID}
      - NOTIFIERS= mailgun://${EMAIL}/${MAILGUN_API}/${EMAIL}
      - TZ=America/New_York
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  traefik-public:
    external: true
